
package cl.facele.docele.sfe.services.reportescsv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReportesCSV", targetNamespace = "http://facele.cl/docele/sfe/services/ReportesCSV/", wsdlLocation = "file:/F:/workspace_chile/facele/procesos_automatizados/src/main/resources/wsdl/estadoActualizacion.wsdl")
public class ReportesCSV_Service
    extends Service
{

    private final static URL REPORTESCSV_WSDL_LOCATION;
    private final static WebServiceException REPORTESCSV_EXCEPTION;
    private final static QName REPORTESCSV_QNAME = new QName("http://facele.cl/docele/sfe/services/ReportesCSV/", "ReportesCSV");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/workspace_chile/facele/procesos_automatizados/src/main/resources/wsdl/estadoActualizacion.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPORTESCSV_WSDL_LOCATION = url;
        REPORTESCSV_EXCEPTION = e;
    }

    public ReportesCSV_Service() {
        super(__getWsdlLocation(), REPORTESCSV_QNAME);
    }

    public ReportesCSV_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPORTESCSV_QNAME, features);
    }

    public ReportesCSV_Service(URL wsdlLocation) {
        super(wsdlLocation, REPORTESCSV_QNAME);
    }

    public ReportesCSV_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPORTESCSV_QNAME, features);
    }

    public ReportesCSV_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportesCSV_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReportesCSV
     */
    @WebEndpoint(name = "ReportesCSVSOAP")
    public ReportesCSV getReportesCSVSOAP() {
        return super.getPort(new QName("http://facele.cl/docele/sfe/services/ReportesCSV/", "ReportesCSVSOAP"), ReportesCSV.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportesCSV
     */
    @WebEndpoint(name = "ReportesCSVSOAP")
    public ReportesCSV getReportesCSVSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://facele.cl/docele/sfe/services/ReportesCSV/", "ReportesCSVSOAP"), ReportesCSV.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPORTESCSV_EXCEPTION!= null) {
            throw REPORTESCSV_EXCEPTION;
        }
        return REPORTESCSV_WSDL_LOCATION;
    }

}
