
package cl.facele.docele.sfe.services.reportescsv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReportesCSV", targetNamespace = "http://facele.cl/docele/sfe/services/ReportesCSV/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReportesCSV {


    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.docele.sfe.services.reportescsv.UploadCSVResponse
     */
    @WebMethod(operationName = "UploadCSV", action = "http://facele.cl/docele/sfe/services/ReportesCSV/UploadCSV")
    @WebResult(name = "UploadCSVResponse", targetNamespace = "http://facele.cl/docele/sfe/services/ReportesCSV/", partName = "parameters")
    public UploadCSVResponse uploadCSV(
        @WebParam(name = "UploadCSV", targetNamespace = "http://facele.cl/docele/sfe/services/ReportesCSV/", partName = "parameters")
        UploadCSV parameters);

}
