
package cl.facele.sfe.cargapropiedadescontribuyente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CargaPropiedadesContribuyente", targetNamespace = "http://facele.cl/sfe/CargaPropiedadesContribuyente/", wsdlLocation = "file:/home/facele/git/dte_recibidos_sii/src/main/resources/wsdl/CargaPropiedadesContribuyenteService.wsdl")
public class CargaPropiedadesContribuyente_Service
    extends Service
{

    private final static URL CARGAPROPIEDADESCONTRIBUYENTE_WSDL_LOCATION;
    private final static WebServiceException CARGAPROPIEDADESCONTRIBUYENTE_EXCEPTION;
    private final static QName CARGAPROPIEDADESCONTRIBUYENTE_QNAME = new QName("http://facele.cl/sfe/CargaPropiedadesContribuyente/", "CargaPropiedadesContribuyente");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/facele/git/dte_recibidos_sii/src/main/resources/wsdl/CargaPropiedadesContribuyenteService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARGAPROPIEDADESCONTRIBUYENTE_WSDL_LOCATION = url;
        CARGAPROPIEDADESCONTRIBUYENTE_EXCEPTION = e;
    }

    public CargaPropiedadesContribuyente_Service() {
        super(__getWsdlLocation(), CARGAPROPIEDADESCONTRIBUYENTE_QNAME);
    }

    public CargaPropiedadesContribuyente_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARGAPROPIEDADESCONTRIBUYENTE_QNAME, features);
    }

    public CargaPropiedadesContribuyente_Service(URL wsdlLocation) {
        super(wsdlLocation, CARGAPROPIEDADESCONTRIBUYENTE_QNAME);
    }

    public CargaPropiedadesContribuyente_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARGAPROPIEDADESCONTRIBUYENTE_QNAME, features);
    }

    public CargaPropiedadesContribuyente_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CargaPropiedadesContribuyente_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CargaPropiedadesContribuyente
     */
    @WebEndpoint(name = "CargaPropiedadesContribuyenteService")
    public CargaPropiedadesContribuyente getCargaPropiedadesContribuyenteService() {
        return super.getPort(new QName("http://facele.cl/sfe/CargaPropiedadesContribuyente/", "CargaPropiedadesContribuyenteService"), CargaPropiedadesContribuyente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CargaPropiedadesContribuyente
     */
    @WebEndpoint(name = "CargaPropiedadesContribuyenteService")
    public CargaPropiedadesContribuyente getCargaPropiedadesContribuyenteService(WebServiceFeature... features) {
        return super.getPort(new QName("http://facele.cl/sfe/CargaPropiedadesContribuyente/", "CargaPropiedadesContribuyenteService"), CargaPropiedadesContribuyente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARGAPROPIEDADESCONTRIBUYENTE_EXCEPTION!= null) {
            throw CARGAPROPIEDADESCONTRIBUYENTE_EXCEPTION;
        }
        return CARGAPROPIEDADESCONTRIBUYENTE_WSDL_LOCATION;
    }

}
