
package cl.facele.sfe.cargapropiedadescontribuyente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CargaPropiedadesContribuyente", targetNamespace = "http://facele.cl/sfe/CargaPropiedadesContribuyente/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CargaPropiedadesContribuyente {


    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.sfe.cargapropiedadescontribuyente.DoCargaPropiedadesContribuyenteResponse
     */
    @WebMethod(action = "http://facele.cl/sfe/CargaPropiedadesContribuyente/doCargaPropiedadesContribuyente")
    @WebResult(name = "doCargaPropiedadesContribuyenteResponse", targetNamespace = "http://facele.cl/sfe/CargaPropiedadesContribuyente/", partName = "parameters")
    public DoCargaPropiedadesContribuyenteResponse doCargaPropiedadesContribuyente(
        @WebParam(name = "doCargaPropiedadesContribuyente", targetNamespace = "http://facele.cl/sfe/CargaPropiedadesContribuyente/", partName = "parameters")
        DoCargaPropiedadesContribuyente parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.sfe.cargapropiedadescontribuyente.ObtenerResponse
     */
    @WebMethod(action = "http://facele.cl/sfe/CargaPropiedadesContribuyente/obtener")
    @WebResult(name = "obtenerResponse", targetNamespace = "http://facele.cl/sfe/CargaPropiedadesContribuyente/", partName = "parameters")
    public ObtenerResponse obtener(
        @WebParam(name = "obtener", targetNamespace = "http://facele.cl/sfe/CargaPropiedadesContribuyente/", partName = "parameters")
        Obtener parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.sfe.cargapropiedadescontribuyente.ConsultarResponse
     */
    @WebMethod(action = "http://facele.cl/sfe/CargaPropiedadesContribuyente/consultar")
    @WebResult(name = "consultarResponse", targetNamespace = "http://facele.cl/sfe/CargaPropiedadesContribuyente/", partName = "parameters")
    public ConsultarResponse consultar(
        @WebParam(name = "consultar", targetNamespace = "http://facele.cl/sfe/CargaPropiedadesContribuyente/", partName = "parameters")
        Consultar parameters);

}
