/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.facele.robot.logica;

import javax.swing.JFrame;

import cl.facele.robot.utilidades.Constantes;

/**
 *
 * @author facele
 */
public class ViewAutomatizacionProceso extends javax.swing.JFrame {

	private static final long serialVersionUID = -1289736130921133713L;

	/**
	 * Creates new form VentanaPrincipal
	 */
	public ViewAutomatizacionProceso() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents


	private void initComponents() {

		jPanelBackground = new javax.swing.JPanel();
		imgFacele = new javax.swing.JLabel();
		labelTitulo = new javax.swing.JLabel();
		separador = new javax.swing.JSeparator();
		decargarRecibidosSII = new javax.swing.JButton();
		repaldarDTESII = new javax.swing.JButton();
		cargarContribuyente = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		imgFacele.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("logoFacele.png"))); // NOI18N

		labelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		labelTitulo.setText("Procesos Automatizados");

		decargarRecibidosSII.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		decargarRecibidosSII.setText("Descargar Recibidos SII");
		decargarRecibidosSII.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				decargarRecibidosSIIActionPerformed(evt);
			}
		});

		repaldarDTESII.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		repaldarDTESII.setText("Respaldar Documentos SII");
		repaldarDTESII.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				repaldarDTESIIActionPerformed(evt);
			}
		});

		cargarContribuyente.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		cargarContribuyente.setText("Cargar Contribuyente");
		cargarContribuyente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				redirectCargaContribuyente(evt);
			}
		});

		javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
		jPanelBackground.setLayout(jPanelBackgroundLayout);
		jPanelBackgroundLayout.setHorizontalGroup(
				jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanelBackgroundLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(separador)
								.addGroup(jPanelBackgroundLayout.createSequentialGroup()
										.addComponent(imgFacele, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
								.addComponent(decargarRecibidosSII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(repaldarDTESII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(cargarContribuyente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap())
				);
		jPanelBackgroundLayout.setVerticalGroup(
				jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanelBackgroundLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(imgFacele))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(decargarRecibidosSII, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(repaldarDTESII, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(cargarContribuyente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(31, Short.MAX_VALUE))
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);

		pack();
	}// </editor-fold>

	
	/**
	 * redirecciona a la ventana de carga contribuyente
	 */
	private void redirectCargaContribuyente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirectCargaContribuyente
		this.dispose();
		JFrame frame = new ViewCargarContribuyente();
		frame.setVisible(true);

	}//GEN-LAST:event_redirectCargaContribuyente

	private void decargarRecibidosSIIActionPerformed(java.awt.event.ActionEvent evt) {                                                     
		
		this.dispose();
		RunnableRespaldoDocumento respaldo = new RunnableRespaldoDocumento();
		Constantes.EXECUTOR.execute(respaldo);
		
	}                                                    

	private void repaldarDTESIIActionPerformed(java.awt.event.ActionEvent evt) {                                               

		this.dispose();
		RunnableDescargaDTE descarga = new RunnableDescargaDTE();
		Constantes.EXECUTOR.execute(descarga);
	}                                            

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cargarContribuyente;
	private javax.swing.JButton decargarRecibidosSII;
	private javax.swing.JLabel imgFacele;
	private javax.swing.JPanel jPanelBackground;
	private javax.swing.JLabel labelTitulo;
	private javax.swing.JButton repaldarDTESII;
	private javax.swing.JSeparator separador;
	// End of variables declaration//GEN-END:variables
}
