package cl.facele.robot.logica;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

import org.apache.log4j.Logger;

import cl.facele.robot.bean.EstadoActualizacionBean;
import cl.facele.robot.utilidades.Constantes;

/**
 *
 * @author facele
 */
@SuppressWarnings("serial")
public class ViewActualizarEstado extends javax.swing.JFrame {

	private Logger logger = Logger.getLogger(getClass());
	
    /**
     * Creates new form ViewCargarContribuyente
     */
    public ViewActualizarEstado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	ambienteList = new ArrayList<String>();
    	
        panelBackground = new javax.swing.JPanel();
        imgFacele = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jScrollTable = new javax.swing.JScrollPane();
        tableAmbiente = new javax.swing.JTable();
        separador = new javax.swing.JSeparator();
        fechaEstado = new com.toedter.calendar.JDateChooser();
        rutContribuyente = new javax.swing.JTextField();
        labelPeriodo = new javax.swing.JLabel();
        labelRUT = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        
        labelPeriodo.setText("Período");
        labelRUT.setText("RUT");
        
        fechaEstado.setDateFormatString("yyyy-MM-dd");
        fechaEstado.setEnabled(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgFacele.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("logoFacele.png"))); // NOI18N

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titulo.setText("Cargar Contribuyente");

        tableAmbiente.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        tableAmbiente.setModel(new javax.swing.table.DefaultTableModel(
            Constantes.TABLE_AMBIENTE,
            new String [] {
                "", "Ambiente"
            }
        ) {
			Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAmbiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAmbienteMouseClicked(evt);
            }
        });
        jScrollTable.setViewportView(tableAmbiente);
        if (tableAmbiente.getColumnModel().getColumnCount() > 0) {
            tableAmbiente.getColumnModel().getColumn(0).setMinWidth(40);
            tableAmbiente.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableAmbiente.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	procesarEstadoActualizacion(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(imgFacele, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(labelRUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fechaEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(rutContribuyente))
                .addGap(48, 48, 48))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgFacele)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rutContribuyente, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(labelRUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptar)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void procesarEstadoActualizacion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarCargaContribuyente
    	
		if(ambienteList.isEmpty()) {
			JOptionPane.showConfirmDialog(null, "No se ha seleccionado ambiente", 
					"Informacion", JOptionPane.OK_CANCEL_OPTION);
			return;
		}
		
		this.dispose();
		
		final EstadoActualizacionBean estadoActualizacion = new EstadoActualizacionBean();
		estadoActualizacion.setFecha(fechaEstado.getDate());
		estadoActualizacion.setListaAmbiente(ambienteList);
		estadoActualizacion.setRut(rutContribuyente.getText());
		
    	RunneableEstadoActualizacion runEstadoActualizacion = new RunneableEstadoActualizacion(estadoActualizacion);
    	Constantes.EXECUTOR.execute(runEstadoActualizacion);    	

    }//GEN-LAST:event_procesarCargaContribuyente

    private void tableAmbienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAmbienteMouseClicked

        int fila = tableAmbiente.getSelectedRow();
        if(fila < 0)
        	return;
        
        TableModel table = tableAmbiente.getModel();
        boolean isSeleccted = new Boolean(table.getValueAt(fila, 0).toString());
        String ambiente = table.getValueAt(fila, 1).toString();
                                       
        if( ambienteList.contains(ambiente) && isSeleccted)
        	return;
        if(!ambienteList.contains(ambiente) && !isSeleccted)
        	return;
        if(ambienteList.contains(ambiente) && !isSeleccted) {
        	ambienteList.remove(ambiente);
        	return;
        }
        ambienteList.add(ambiente);
        
    }//GEN-LAST:event_tableAmbienteMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel imgFacele;
    private javax.swing.JScrollPane jScrollTable;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tableAmbiente;
    private javax.swing.JLabel titulo;
    private List<String> ambienteList;
    private com.toedter.calendar.JDateChooser fechaEstado;
    private javax.swing.JTextField rutContribuyente;
    private javax.swing.JLabel labelPeriodo;
    private javax.swing.JLabel labelRUT;
    // End of variables declaration//GEN-END:variables
}
