package cl.facele.robot.logica;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

import org.apache.log4j.Logger;

import cl.facele.robot.bean.EstadoActualizacionBean;
import cl.facele.robot.utilidades.Constantes;

/**
 *
 * @author facele
 */
@SuppressWarnings("serial")
public class ViewActualizarEstado extends javax.swing.JFrame {

	private Logger logger = Logger.getLogger(getClass());
	
    /**
     * Creates new form ViewCargarContribuyente
     */
    public ViewActualizarEstado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	ambienteList = new ArrayList<String>();

        panelBackground = new javax.swing.JPanel();
        imgFacele = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jScrollTable = new javax.swing.JScrollPane();
        tableAmbiente = new javax.swing.JTable();
        separador = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        labelPeriodo = new javax.swing.JLabel();
        labelRUT = new javax.swing.JLabel();
        rutContribuyente = new javax.swing.JTextField();
        periodo = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgFacele.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("logoFacele.png"))); // NOI18N

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titulo.setText("Cargar Contribuyente");

        tableAmbiente.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        tableAmbiente.setModel(new javax.swing.table.DefaultTableModel(
                Constantes.TABLE_AMBIENTE,
                new String [] {
                    "", "Ambiente"
                }
            ) {
    			Class[] types = new Class [] {
                    java.lang.Boolean.class, java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
        tableAmbiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAmbienteMouseClicked(evt);
            }
        });
        jScrollTable.setViewportView(tableAmbiente);
        if (tableAmbiente.getColumnModel().getColumnCount() > 0) {
            tableAmbiente.getColumnModel().getColumn(0).setMinWidth(40);
            tableAmbiente.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableAmbiente.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        labelPeriodo.setText("Período (YYYY-MM)");

        labelRUT.setText("RUT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rutContribuyente)
                    .addComponent(periodo, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(periodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRUT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rutContribuyente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        periodo.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(imgFacele, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgFacele)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	procesarEstadoActualizacion(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(aceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * 
     * @param evt
     */
    private void procesarEstadoActualizacion(java.awt.event.ActionEvent evt) {
    	
		if(ambienteList.isEmpty()) {
			JOptionPane.showConfirmDialog(null, "No se ha seleccionado ambiente", 
					"Informacion", JOptionPane.OK_CANCEL_OPTION);
			return;
		}
		
		if ( periodo.getText().equals("") ) {
			JOptionPane.showConfirmDialog(null, "No se ha seleccionado periodo", 
					"Informacion", JOptionPane.OK_CANCEL_OPTION);
			return;
		}
		 
		
		this.dispose();
		
		final EstadoActualizacionBean estadoActualizacion = new EstadoActualizacionBean();

		String array[] = periodo.getText().split("-");
		
		estadoActualizacion.setPeriodoAnio(array[0]);
		estadoActualizacion.setPeriodoMes(array[1]);
		estadoActualizacion.setListaAmbiente(ambienteList);
		estadoActualizacion.setRut(rutContribuyente.getText());
		
    	RunneableEstadoActualizacion runEstadoActualizacion = new RunneableEstadoActualizacion(estadoActualizacion);
    	Constantes.EXECUTOR.execute(runEstadoActualizacion);    	

    }//GEN-LAST:event_procesarCargaContribuyente

    private void tableAmbienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAmbienteMouseClicked

        int fila = tableAmbiente.getSelectedRow();
        if(fila < 0)
        	return;
        
        TableModel table = tableAmbiente.getModel();
        boolean isSeleccted = new Boolean(table.getValueAt(fila, 0).toString());
        String ambiente = table.getValueAt(fila, 1).toString();
                                       
        if( ambienteList.contains(ambiente) && isSeleccted)
        	return;
        if(!ambienteList.contains(ambiente) && !isSeleccted)
        	return;
        if(ambienteList.contains(ambiente) && !isSeleccted) {
        	ambienteList.remove(ambiente);
        	return;
        }
        ambienteList.add(ambiente);
        
    }//GEN-LAST:event_tableAmbienteMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel imgFacele;
    private javax.swing.JScrollPane jScrollTable;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tableAmbiente;
    private javax.swing.JLabel titulo;
    private List<String> ambienteList;
    private com.toedter.calendar.JDateChooser fechaEstado;
    private javax.swing.JTextField rutContribuyente;
    private javax.swing.JLabel labelPeriodo;
    private javax.swing.JLabel labelRUT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField periodo;
    // End of variables declaration//GEN-END:variables
}
