
package cl.facele.egasa.servicios.abonado;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Abonado", targetNamespace = "http://facele.cl/egasa/servicios/Abonado/", wsdlLocation = "file:/home/jose/git/facilitos.git/facilitos/src/main/webapp/WEB-INF/wsdl/Abonado.wsdl")
public class Abonado_Service
    extends Service
{

    private final static URL ABONADO_WSDL_LOCATION;
    private final static WebServiceException ABONADO_EXCEPTION;
    private final static QName ABONADO_QNAME = new QName("http://facele.cl/egasa/servicios/Abonado/", "Abonado");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jose/git/facilitos.git/facilitos/src/main/webapp/WEB-INF/wsdl/Abonado.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ABONADO_WSDL_LOCATION = url;
        ABONADO_EXCEPTION = e;
    }

    public Abonado_Service() {
        super(__getWsdlLocation(), ABONADO_QNAME);
    }

    public Abonado_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ABONADO_QNAME, features);
    }

    public Abonado_Service(URL wsdlLocation) {
        super(wsdlLocation, ABONADO_QNAME);
    }

    public Abonado_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ABONADO_QNAME, features);
    }

    public Abonado_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Abonado_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Abonado
     */
    @WebEndpoint(name = "AbonadoSOAP")
    public Abonado getAbonadoSOAP() {
        return super.getPort(new QName("http://facele.cl/egasa/servicios/Abonado/", "AbonadoSOAP"), Abonado.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Abonado
     */
    @WebEndpoint(name = "AbonadoSOAP")
    public Abonado getAbonadoSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://facele.cl/egasa/servicios/Abonado/", "AbonadoSOAP"), Abonado.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ABONADO_EXCEPTION!= null) {
            throw ABONADO_EXCEPTION;
        }
        return ABONADO_WSDL_LOCATION;
    }

}
