
package cl.docele.ws.documentosrecibidos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocumentosRecibidos", targetNamespace = "http://ws.docele.cl/DocumentosRecibidos/", wsdlLocation = "file:/home/jose/DESAROLLO/PROYECTOS/FACELE_NEON/dte_recibidos_sii/src/main/resources/wsdl/DocumentosRecibidosService.wsdl")
public class DocumentosRecibidos_Service
    extends Service
{

    private final static URL DOCUMENTOSRECIBIDOS_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTOSRECIBIDOS_EXCEPTION;
    private final static QName DOCUMENTOSRECIBIDOS_QNAME = new QName("http://ws.docele.cl/DocumentosRecibidos/", "DocumentosRecibidos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jose/DESAROLLO/PROYECTOS/FACELE_NEON/dte_recibidos_sii/src/main/resources/wsdl/DocumentosRecibidosService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCUMENTOSRECIBIDOS_WSDL_LOCATION = url;
        DOCUMENTOSRECIBIDOS_EXCEPTION = e;
    }

    public DocumentosRecibidos_Service() {
        super(__getWsdlLocation(), DOCUMENTOSRECIBIDOS_QNAME);
    }

    public DocumentosRecibidos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTOSRECIBIDOS_QNAME, features);
    }

    public DocumentosRecibidos_Service(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTOSRECIBIDOS_QNAME);
    }

    public DocumentosRecibidos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTOSRECIBIDOS_QNAME, features);
    }

    public DocumentosRecibidos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentosRecibidos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentosRecibidos
     */
    @WebEndpoint(name = "DocumentosRecibidosSOAP")
    public DocumentosRecibidos getDocumentosRecibidosSOAP() {
        return super.getPort(new QName("http://ws.docele.cl/DocumentosRecibidos/", "DocumentosRecibidosSOAP"), DocumentosRecibidos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentosRecibidos
     */
    @WebEndpoint(name = "DocumentosRecibidosSOAP")
    public DocumentosRecibidos getDocumentosRecibidosSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.docele.cl/DocumentosRecibidos/", "DocumentosRecibidosSOAP"), DocumentosRecibidos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTOSRECIBIDOS_EXCEPTION!= null) {
            throw DOCUMENTOSRECIBIDOS_EXCEPTION;
        }
        return DOCUMENTOSRECIBIDOS_WSDL_LOCATION;
    }

}
