
package cl.facele.sfe.recepciondte;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecepcionDTE", targetNamespace = "http://facele.cl/sfe/RecepcionDTE/", wsdlLocation = "file:/home/facele/git/dte_recibidos_sii/src/main/resources/wsdl/DoceleOLService.wsdl")
public class RecepcionDTE_Service
    extends Service
{

    private final static URL RECEPCIONDTE_WSDL_LOCATION;
    private final static WebServiceException RECEPCIONDTE_EXCEPTION;
    private final static QName RECEPCIONDTE_QNAME = new QName("http://facele.cl/sfe/RecepcionDTE/", "RecepcionDTE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/facele/git/dte_recibidos_sii/src/main/resources/wsdl/DoceleOLService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEPCIONDTE_WSDL_LOCATION = url;
        RECEPCIONDTE_EXCEPTION = e;
    }

    public RecepcionDTE_Service() {
        super(__getWsdlLocation(), RECEPCIONDTE_QNAME);
    }

    public RecepcionDTE_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEPCIONDTE_QNAME, features);
    }

    public RecepcionDTE_Service(URL wsdlLocation) {
        super(wsdlLocation, RECEPCIONDTE_QNAME);
    }

    public RecepcionDTE_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEPCIONDTE_QNAME, features);
    }

    public RecepcionDTE_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecepcionDTE_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecepcionDTE
     */
    @WebEndpoint(name = "RecepcionDTESOAP")
    public RecepcionDTE getRecepcionDTESOAP() {
        return super.getPort(new QName("http://facele.cl/sfe/RecepcionDTE/", "RecepcionDTESOAP"), RecepcionDTE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecepcionDTE
     */
    @WebEndpoint(name = "RecepcionDTESOAP")
    public RecepcionDTE getRecepcionDTESOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://facele.cl/sfe/RecepcionDTE/", "RecepcionDTESOAP"), RecepcionDTE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEPCIONDTE_EXCEPTION!= null) {
            throw RECEPCIONDTE_EXCEPTION;
        }
        return RECEPCIONDTE_WSDL_LOCATION;
    }

}
