
package cl.facele.sfe.recepciondte;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "RecepcionDTESOAP", serviceName = "RecepcionDTE", targetNamespace = "http://facele.cl/sfe/RecepcionDTE/", wsdlLocation = "file:/home/facele/git/dte_recibidos_sii/src/main/resources/wsdl/DoceleOLService.wsdl", endpointInterface = "cl.facele.sfe.recepciondte.RecepcionDTE")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class RecepcionDTE_RecepcionDTESOAPImpl
    implements RecepcionDTE
{


    public RecepcionDTE_RecepcionDTESOAPImpl() {
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.sfe.recepciondte.UpLoadRegistroSIIResponse
     */
    public UpLoadRegistroSIIResponse upLoadRegistroSII(UpLoadRegistroSII parameters) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.sfe.recepciondte.UpLoadArchivoIntercambioResponse
     */
    public UpLoadArchivoIntercambioResponse upLoadArchivoIntercambio(UpLoadArchivoIntercambio parameters) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.sfe.recepciondte.ConsultaDTEPendientesRecepcionResponse
     */
    public ConsultaDTEPendientesRecepcionResponse consultaDTEPendientesRecepcion(ConsultaDTEPendientesRecepcion parameters) {
        //replace with your impl here
        return null;
    }

}
