
package cl.facele.sfe.recepciondte;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecepcionDTE", targetNamespace = "http://facele.cl/sfe/RecepcionDTE/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecepcionDTE {


    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.sfe.recepciondte.UpLoadRegistroSIIResponse
     */
    @WebMethod(operationName = "UpLoadRegistroSII", action = "http://facele.cl/sfe/RecepcionDTE/UpLoadRegistroSII")
    @WebResult(name = "UpLoadRegistroSIIResponse", targetNamespace = "http://facele.cl/sfe/RecepcionDTE/", partName = "parameters")
    public UpLoadRegistroSIIResponse upLoadRegistroSII(
        @WebParam(name = "UpLoadRegistroSII", targetNamespace = "http://facele.cl/sfe/RecepcionDTE/", partName = "parameters")
        UpLoadRegistroSII parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.sfe.recepciondte.UpLoadArchivoIntercambioResponse
     */
    @WebMethod(operationName = "UpLoadArchivoIntercambio", action = "http://facele.cl/sfe/RecepcionDTE/UpLoadArchivoIntercambio")
    @WebResult(name = "UpLoadArchivoIntercambioResponse", targetNamespace = "http://facele.cl/sfe/RecepcionDTE/", partName = "parameters")
    public UpLoadArchivoIntercambioResponse upLoadArchivoIntercambio(
        @WebParam(name = "UpLoadArchivoIntercambio", targetNamespace = "http://facele.cl/sfe/RecepcionDTE/", partName = "parameters")
        UpLoadArchivoIntercambio parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns cl.facele.sfe.recepciondte.ConsultaDTEPendientesRecepcionResponse
     */
    @WebMethod(operationName = "ConsultaDTEPendientesRecepcion", action = "http://facele.cl/sfe/RecepcionDTE/ConsultaDTEPendientesRecepcion")
    @WebResult(name = "ConsultaDTEPendientesRecepcionResponse", targetNamespace = "http://facele.cl/sfe/RecepcionDTE/", partName = "parameters")
    public ConsultaDTEPendientesRecepcionResponse consultaDTEPendientesRecepcion(
        @WebParam(name = "ConsultaDTEPendientesRecepcion", targetNamespace = "http://facele.cl/sfe/RecepcionDTE/", partName = "parameters")
        ConsultaDTEPendientesRecepcion parameters);

}
