
package cl.facele.egasa.impl;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import com.sun.xml.ws.developer.SchemaValidation;

import cl.facele.egasa.servicios.abonado.Abonado;
import cl.facele.egasa.servicios.abonado.Crear;
import cl.facele.egasa.servicios.abonado.CrearResponse;
import cl.facele.egasa.servicios.abonado.Obtener;
import cl.facele.egasa.servicios.abonado.ObtenerResponse;
import cl.facele.egasa.servicios.abonado.Respuesta;

/**
 * This class was generated by the JAX-WS RI.	
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "AbonadoSOAP", serviceName = "Abonado", targetNamespace = "http://facele.pe/egasa/servicios/Abonado/", endpointInterface = "cl.facele.egasa.servicios.abonado.Abonado")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@SchemaValidation
public class AbonadoSOAPImpl
implements Abonado
{


	public AbonadoSOAPImpl() {
	}

	/**
	 * 
	 * @param parameters
	 * @return
	 *     returns cl.facele.egasa.servicios.abonado.CrearResponse
	 */
	public CrearResponse crear(Crear parameters) {
		//replace with your impl here
		Respuesta respuesta = null; 
		CrearResponse crearResponse = null; 
		try {
			respuesta = new Respuesta();
			crearResponse = new CrearResponse();
			crearResponse.setRespuesta(respuesta);
		} catch (Exception e) {
			e.printStackTrace();
			crearResponse = null;
		}
		return crearResponse;
	}

	/**
	 * 
	 * @param parameters
	 * @return
	 *     returns cl.facele.egasa.servicios.abonado.ObtenerResponse
	 */
	public ObtenerResponse obtener(Obtener parameters) {
		//replace with your impl here
		return null;
	}

}
