
package cl.facele.sfe.cargacontribuyenteselectronicos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CargaContribuyentesElectronicos", targetNamespace = "http://facele.cl/sfe/CargaContribuyentesElectronicos/", wsdlLocation = "file:/home/facele/DESARROLLO/PROYECTO/facele/procesos_automatizados/src/main/resources/wsdl/CargaContribuyentesElectronicosService.wsdl")
public class CargaContribuyentesElectronicos_Service
    extends Service
{

    private final static URL CARGACONTRIBUYENTESELECTRONICOS_WSDL_LOCATION;
    private final static WebServiceException CARGACONTRIBUYENTESELECTRONICOS_EXCEPTION;
    private final static QName CARGACONTRIBUYENTESELECTRONICOS_QNAME = new QName("http://facele.cl/sfe/CargaContribuyentesElectronicos/", "CargaContribuyentesElectronicos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/facele/DESARROLLO/PROYECTO/facele/procesos_automatizados/src/main/resources/wsdl/CargaContribuyentesElectronicosService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARGACONTRIBUYENTESELECTRONICOS_WSDL_LOCATION = url;
        CARGACONTRIBUYENTESELECTRONICOS_EXCEPTION = e;
    }

    public CargaContribuyentesElectronicos_Service() {
        super(__getWsdlLocation(), CARGACONTRIBUYENTESELECTRONICOS_QNAME);
    }

    public CargaContribuyentesElectronicos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARGACONTRIBUYENTESELECTRONICOS_QNAME, features);
    }

    public CargaContribuyentesElectronicos_Service(URL wsdlLocation) {
        super(wsdlLocation, CARGACONTRIBUYENTESELECTRONICOS_QNAME);
    }

    public CargaContribuyentesElectronicos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARGACONTRIBUYENTESELECTRONICOS_QNAME, features);
    }

    public CargaContribuyentesElectronicos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CargaContribuyentesElectronicos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CargaContribuyentesElectronicos
     */
    @WebEndpoint(name = "CargaContribuyentesElectronicosService")
    public CargaContribuyentesElectronicos getCargaContribuyentesElectronicosService() {
        return super.getPort(new QName("http://facele.cl/sfe/CargaContribuyentesElectronicos/", "CargaContribuyentesElectronicosService"), CargaContribuyentesElectronicos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CargaContribuyentesElectronicos
     */
    @WebEndpoint(name = "CargaContribuyentesElectronicosService")
    public CargaContribuyentesElectronicos getCargaContribuyentesElectronicosService(WebServiceFeature... features) {
        return super.getPort(new QName("http://facele.cl/sfe/CargaContribuyentesElectronicos/", "CargaContribuyentesElectronicosService"), CargaContribuyentesElectronicos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARGACONTRIBUYENTESELECTRONICOS_EXCEPTION!= null) {
            throw CARGACONTRIBUYENTESELECTRONICOS_EXCEPTION;
        }
        return CARGACONTRIBUYENTESELECTRONICOS_WSDL_LOCATION;
    }

}
